# Generated by Django 3.2.9 on 2021-12-02 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurancecompany', '0001_initial'),
        ('patient', '0004_alter_patient_options'),
        ('Web_app', '0003_auto_20211202_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_status_code', models.CharField(max_length=8)),
                ('status_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('claim_number', models.IntegerField(primary_key=True, serialize=False)),
                ('detail', models.TextField()),
                ('updated_date', models.DateField()),
                ('claim_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claim.claimstatus')),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_app.hospital')),
                ('insurancecompany_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurancecompany.company')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
