# Generated by Django 3.2.9 on 2021-12-02 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_mobile_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name_plural': 'Patient Info'},
        ),
    ]
