# Generated by Django 3.2.9 on 2021-12-02 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_app', '0002_auto_20211107_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name_plural': 'Hospital'},
        ),
        migrations.AlterModelOptions(
            name='hospital_type',
            options={'verbose_name_plural': 'Hospital type'},
        ),
    ]
