# Generated by Django 3.2.9 on 2021-12-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_app', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
